# Generated by Django 6.1 on 2026-10-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_starred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
